[package]
name = "cditor-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cditor-config = { path = "../cditor-config" }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = { version = "1", features = ["raw_value"] }
unicode-segmentation = "1.12"
uuid = { version = "1", features = ["v7", "serde"] }
getrandom = "0.3"
