[workspace]
members = [
    "crates/cditor-ai",
    "crates/cditor-core",
    "crates/cditor-editor-protocol",
    "crates/cditor-theme",
    "crates/cditor-storage",
    "crates/cditor-storage-postgres",
    "crates/cditor-storage-sqlite",
    "crates/cditor-runtime",
    "crates/cditor-session",
    "crates/cditor-viewport",
    "crates/cditor-editor-gpui",
    "crates/cditor-import-export",
    "crates/cditor-api",
    "crates/cditor-app",
    "crates/cditor-test-support",
    "crates/cditor-text",
    "components/cditor-whiteboard",
]
default-members = ["crates/cditor-app"]
resolver = "3"

[workspace.package]
version = "0.2.6"
edition = "2024"
license = "GPL-3.0-or-later"

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1
