use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ColorToken {
    Surface,
    Page,
    Panel,
    Text,
    Muted,
    Border,
    StrongBorder,
    Focused,
    HoverSurface,
    ActionBackground,
    ActionHoverBackground,
    ActionAccent,
    GutterBackground,
    GutterForeground,
    PrefixText,
    QuoteText,
    QuoteBar,
    CalloutBackground,
    CalloutBorder,
    CalloutIconBackground,
    CheckboxBorder,
    CheckboxCheckedBackground,
    CheckboxCheckedText,
    CodeBackground,
    CodeText,
    InlineCodeBackground,
    InlineCodeText,
    CodeToolbarBackground,
    CodeToolbarBorder,
    CodeToolbarText,
    CodeToolbarIcon,
    CodeToolbarHover,
    TableHeaderBackground,
    TableActiveBorder,
    Skeleton,
    Danger,
    Scrollbar,
    ScrollbarHover,
}
