[package]
name = "cditor-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "cditor_api"

[dependencies]
async-trait = "0.1"
cditor-ai = { path = "../cditor-ai" }
cditor-core = { path = "../cditor-core" }
cditor-editor-protocol = { path = "../cditor-editor-protocol" }
cditor-storage = { path = "../cditor-storage" }
cditor-theme = { path = "../cditor-theme" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "1d217ee39d381ac101b7cf49d3d22451ac1093fe", default-features = false, features = ["font-kit"] }
thiserror = "1"
